ls -l /u02/app/oracle/oradata/datastore/.ACFS/snaps/os_st/OS_ST/datafile/o1_mf_system_e8ql6c67_.dbf
ls -l /u02/app/oracle/oradata/datastore/.ACFS/snaps/os_st/OS_ST/datafile/o1_mf_undotbs1_d8ql5mmn_.dbf
ls -l /u02/app/oracle/oradata/datastore/.ACFS/snaps/os_st/OS_ST/datafile/o1_mf_sysaux_deql5uka_.dbf
ls -l /u02/app/oracle/oradata/datastore/.ACFS/snaps/os_st/OS_ST/datafile/o1_mf_undotbs2_d9ql5qmd_.dbf
ls -l /u02/app/oracle/oradata/datastore/.ACFS/snaps/os_st/OS_ST/datafile/o1_mf_users_e2ql6at2_.dbf
ls -l /u02/app/oracle/oradata/datastore/.ACFS/snaps/os_st/OS_ST/datafile/o1_mf_datamart_e6ql6bms_.dbf
ls -l /u02/app/oracle/oradata/datastore/.ACFS/snaps/os_st/OS_ST/datafile/o1_mf_datamart_e7ql6bn4_.dbf
ls -l /u02/app/oracle/oradata/datastore/.ACFS/snaps/os_st/OS_ST/datafile/o1_mf_md_indx_eaql6cf6_.dbf
ls -l /u02/app/oracle/oradata/datastore/.ACFS/snaps/os_st/OS_ST/datafile/o1_mf_storage__cbql4qrg_.dbf
ls -l /u02/app/oracle/oradata/datastore/.ACFS/snaps/os_st/OS_ST/datafile/o1_mf_storage__cdql4u20_.dbf
ls -l /u02/app/oracle/oradata/datastore/.ACFS/snaps/os_st/OS_ST/datafile/o1_mf_lob_data_dfql5v5k_.dbf
ls -l /u02/app/oracle/oradata/datastore/.ACFS/snaps/os_st/OS_ST/datafile/o1_mf_lob_data_dgql601o_.dbf
ls -l /u02/app/oracle/oradata/datastore/.ACFS/snaps/os_st/OS_ST/datafile/o1_mf_lob_data_c4ql4ok6_.dbf
ls -l /u02/app/oracle/oradata/datastore/.ACFS/snaps/os_st/OS_ST/datafile/o1_mf_object_i_dhql6045_.dbf
ls -l /u02/app/oracle/oradata/datastore/.ACFS/snaps/os_st/OS_ST/datafile/o1_mf_object_i_diql60u2_.dbf
ls -l /u02/app/oracle/oradata/datastore/.ACFS/snaps/os_st/OS_ST/datafile/o1_mf_object_i_d5ql5kdr_.dbf
ls -l /u02/app/oracle/oradata/datastore/.ACFS/snaps/os_st/OS_ST/datafile/o1_mf_meta_dat_e9ql6c7c_.dbf
ls -l /u02/app/oracle/oradata/datastore/.ACFS/snaps/os_st/OS_ST/datafile/o1_mf_object_d_ceql50a5_.dbf
ls -l /u02/app/oracle/oradata/datastore/.ACFS/snaps/os_st/OS_ST/datafile/o1_mf_object_d_cfql50h0_.dbf
ls -l /u02/app/oracle/oradata/datastore/.ACFS/snaps/os_st/OS_ST/datafile/o1_mf_object_d_cgql50rb_.dbf
ls -l /u02/app/oracle/oradata/datastore/.ACFS/snaps/os_st/OS_ST/datafile/o1_mf_object_d_chql50sg_.dbf
ls -l /u02/app/oracle/oradata/datastore/.ACFS/snaps/os_st/OS_ST/datafile/o1_mf_object_d_ciql540s_.dbf
ls -l /u02/app/oracle/oradata/datastore/.ACFS/snaps/os_st/OS_ST/datafile/o1_mf_object_d_c5ql4ok6_.dbf
ls -l /u02/app/oracle/oradata/datastore/.ACFS/snaps/os_st/OS_ST/datafile/o1_mf_repo_ebql6cih_.dbf
ls -l /u02/app/oracle/oradata/datastore/.ACFS/snaps/os_st/OS_ST/datafile/o1_mf_lob_data_c6ql4ok7_.dbf
ls -l /u02/app/oracle/oradata/datastore/.ACFS/snaps/os_st/OS_ST/datafile/o1_mf_lob_data_daql5r81_.dbf
ls -l /u02/app/oracle/oradata/datastore/.ACFS/snaps/os_st/OS_ST/datafile/o1_mf_object_i_d6ql5m3k_.dbf
ls -l /u02/app/oracle/oradata/datastore/.ACFS/snaps/os_st/OS_ST/datafile/o1_mf_object_d_c7ql4ok7_.dbf
ls -l /u02/app/oracle/oradata/datastore/.ACFS/snaps/os_st/OS_ST/datafile/o1_mf_object_d_c8ql4ohv_.dbf
ls -l /u02/app/oracle/oradata/datastore/.ACFS/snaps/os_st/OS_ST/datafile/o1_mf_lob_data_c9ql4oma_.dbf
ls -l /u02/app/oracle/oradata/datastore/.ACFS/snaps/os_st/OS_ST/datafile/o1_mf_object_i_ccql4r4i_.dbf
ls -l /u02/app/oracle/oradata/datastore/.ACFS/snaps/os_st/OS_ST/datafile/o1_mf_object_d_cjql549l_.dbf
ls -l /u02/app/oracle/oradata/datastore/.ACFS/snaps/os_st/OS_ST/datafile/o1_mf_object_d_ckql54m7_.dbf
ls -l /u02/app/oracle/oradata/datastore/.ACFS/snaps/os_st/OS_ST/datafile/o1_mf_object_i_d7ql5mh5_.dbf
ls -l /u02/app/oracle/oradata/datastore/.ACFS/snaps/os_st/OS_ST/datafile/o1_mf_object_d_clql54ps_.dbf
ls -l /u02/app/oracle/oradata/datastore/.ACFS/snaps/os_st/OS_ST/datafile/o1_mf_lob_data_caql4qm7_.dbf
ls -l /u02/app/oracle/oradata/datastore/.ACFS/snaps/os_st/OS_ST/datafile/o1_mf_storage__d3ql5jk3_.dbf
ls -l /u02/app/oracle/oradata/datastore/.ACFS/snaps/os_st/OS_ST/datafile/o1_mf_object_d_cmql57ke_.dbf
ls -l /u02/app/oracle/oradata/datastore/.ACFS/snaps/os_st/OS_ST/datafile/o1_mf_object_d_cnql57vd_.dbf
ls -l /u02/app/oracle/oradata/datastore/.ACFS/snaps/os_st/OS_ST/datafile/o1_mf_lob_data_djql61ih_.dbf
ls -l /u02/app/oracle/oradata/datastore/.ACFS/snaps/os_st/OS_ST/datafile/o1_mf_object_d_coql589e_.dbf
ls -l /u02/app/oracle/oradata/datastore/.ACFS/snaps/os_st/OS_ST/datafile/o1_mf_lob_data_dkql62nr_.dbf
ls -l /u02/app/oracle/oradata/datastore/.ACFS/snaps/os_st/OS_ST/datafile/o1_mf_object_d_cpql58iq_.dbf
ls -l /u02/app/oracle/oradata/datastore/.ACFS/snaps/os_st/OS_ST/datafile/o1_mf_lob_data_dlql62pu_.dbf
ls -l /u02/app/oracle/oradata/datastore/.ACFS/snaps/os_st/OS_ST/datafile/o1_mf_object_d_cqql5b4g_.dbf
ls -l /u02/app/oracle/oradata/datastore/.ACFS/snaps/os_st/OS_ST/datafile/o1_mf_object_d_crql5bj9_.dbf
ls -l /u02/app/oracle/oradata/datastore/.ACFS/snaps/os_st/OS_ST/datafile/o1_mf_lob_data_dmql63ln_.dbf
ls -l /u02/app/oracle/oradata/datastore/.ACFS/snaps/os_st/OS_ST/datafile/o1_mf_lob_data_dnql64hg_.dbf
ls -l /u02/app/oracle/oradata/datastore/.ACFS/snaps/os_st/OS_ST/datafile/o1_mf_object_d_csql5bu8_.dbf
ls -l /u02/app/oracle/oradata/datastore/.ACFS/snaps/os_st/OS_ST/datafile/o1_mf_storage__d4ql5jnf_.dbf
ls -l /u02/app/oracle/oradata/datastore/.ACFS/snaps/os_st/OS_ST/datafile/o1_mf_storage__doql6535_.dbf
ls -l /u02/app/oracle/oradata/datastore/.ACFS/snaps/os_st/OS_ST/datafile/o1_mf_object_i_dpql6583_.dbf
ls -l /u02/app/oracle/oradata/datastore/.ACFS/snaps/os_st/OS_ST/datafile/o1_mf_object_d_ctql5c3h_.dbf
ls -l /u02/app/oracle/oradata/datastore/.ACFS/snaps/os_st/OS_ST/datafile/o1_mf_lob_data_dqql6629_.dbf
ls -l /u02/app/oracle/oradata/datastore/.ACFS/snaps/os_st/OS_ST/datafile/o1_mf_object_d_cuql5f8t_.dbf
ls -l /u02/app/oracle/oradata/datastore/.ACFS/snaps/os_st/OS_ST/datafile/o1_mf_lob_data_drql6709_.dbf
ls -l /u02/app/oracle/oradata/datastore/.ACFS/snaps/os_st/OS_ST/datafile/o1_mf_object_d_cvql5fnl_.dbf
ls -l /u02/app/oracle/oradata/datastore/.ACFS/snaps/os_st/OS_ST/datafile/o1_mf_object_d_d0ql5fvf_.dbf
ls -l /u02/app/oracle/oradata/datastore/.ACFS/snaps/os_st/OS_ST/datafile/o1_mf_lob_data_dsql67m1_.dbf
ls -l /u02/app/oracle/oradata/datastore/.ACFS/snaps/os_st/OS_ST/datafile/o1_mf_object_i_dvql69jg_.dbf
ls -l /u02/app/oracle/oradata/datastore/.ACFS/snaps/os_st/OS_ST/datafile/o1_mf_object_d_d1ql5gb3_.dbf
ls -l /u02/app/oracle/oradata/datastore/.ACFS/snaps/os_st/OS_ST/datafile/o1_mf_storage__e5ql6bl3_.dbf
ls -l /u02/app/oracle/oradata/datastore/.ACFS/snaps/os_st/OS_ST/datafile/o1_mf_lob_data_dtql67n6_.dbf
ls -l /u02/app/oracle/oradata/datastore/.ACFS/snaps/os_st/OS_ST/datafile/o1_mf_object_d_ddql5ta8_.dbf
ls -l /u02/app/oracle/oradata/datastore/.ACFS/snaps/os_st/OS_ST/datafile/o1_mf_lob_data_duql68bm_.dbf
ls -l /u02/app/oracle/oradata/datastore/.ACFS/snaps/os_st/OS_ST/datafile/o1_mf_storage__d2ql5iqs_.dbf
ls -l /u02/app/oracle/oradata/datastore/.ACFS/snaps/os_st/OS_ST/datafile/o1_mf_lob_data_dcql5t6t_.dbf
ls -l /u02/app/oracle/oradata/datastore/.ACFS/snaps/os_st/OS_ST/datafile/o1_mf_storage__e4ql6aun_.dbf
ls -l /u02/app/oracle/oradata/datastore/.ACFS/snaps/os_st/OS_ST/datafile/o1_mf_object_d_dbql5sm7_.dbf
ls -l /u02/app/oracle/oradata/datastore/.ACFS/snaps/os_st/OS_ST/datafile/o1_mf_object_i_efql6co4_.dbf
ls -l /u02/app/oracle/oradata/datastore/.ACFS/snaps/os_st/OS_ST/datafile/o1_mf_lob_data_e3ql6ati_.dbf
ls -l /u02/app/oracle/oradata/datastore/.ACFS/snaps/os_st/OS_ST/datafile/o1_mf_object_d_e0ql6a5p_.dbf
ls -l /u02/app/oracle/oradata/datastore/.ACFS/snaps/os_st/OS_ST/datafile/o1_mf_object_d_e1ql6a61_.dbf
ls -l /u02/app/oracle/oradata/datastore/.ACFS/snaps/os_st/OS_ST/datafile/o1_mf_lob_data_ecql6cku_.dbf
ls -l /u02/app/oracle/oradata/datastore/.ACFS/snaps/os_st/OS_ST/datafile/o1_mf_lob_data_edql6clp_.dbf
ls -l /u02/app/oracle/oradata/datastore/.ACFS/snaps/os_st/OS_ST/datafile/o1_mf_object_i_eeql6cns_.dbf
ls -l /u02/app/oracle/oradata/datastore/.ACFS/snaps/os_st/OS_ST/datafile/o1_mf_lob_data_egql6co7_.dbf

