 SELECT *
  FROM (SELECT /*+ first_rows */
		T0.BUSINESS_VARIABLE_ID ROWID1, T0.BUSINESS_VARIABLE_ID, T0.CONTAINER_OBJECT_TYPE_ID, T0.BUSINESS_VARIABLE_NAME, T0.BUSINESS_VARIABLE_CALCULATION,
		T0.LOGICAL_DATA_TYPE_ID, T0.BUSINESS_VARIABLE_DESC, T0.REFERENCED_OBJECT_TYPE_ID, T0.LOOKUP_LIST_ID, T0.HILIMIT, T0.LOLIMIT, T0.ENCRYPT_TF,
		T0.DEFAULT_COLUMN_NAME, T0.PRECISION, T0.LENGTH, T0.FLR_STARTING_POSITION, T0.SEQUENCE_NUMBER, T0.MASK_ON_UI, T0.FORMAT_MASK, T0.DOMINATOR_BV_ID,
		T0.TAG, T0.XML_TAG_TYPE_CODE, T0.INCL_OBJECT_RELATIONSHIP_ID, T0.DEFAULT_VALUE, T0.COMMENTS, T0.TP_DICTIONARY_ID, T0.XML_NILLABLE_TF, T0.XML_EMPTY_TAG_TF,
		T0.XML_DEFAULT_VALUE, T0.XML_RENDER_TF, T0.XML_ATTRIBUTE_TF
	   FROM DW_MD.BUSINESS_VARIABLE@ST_DW_MD T0 , DW_MD.OBJECT_TYPE@ST_DW_MD T2, DW_MD.RULE@ST_DW_MD T4, DW_MD.LOGICAL_DATA_TYPE@ST_DW_MD T5, DW_MD.OBJECT_TYPE@ST_DW_MD T7
		, DW_MD.LOOKUP_LIST@ST_DW_MD T8, DW_MD.BUSINESS_VARIABLE@ST_DW_MD T19, DW_MD.OBJECT_RELATIONSHIP@ST_DW_MD T22, DW_MD.DICTIONARY@ST_DW_MD T25
	  WHERE (T0.CONTAINER_OBJECT_TYPE_ID = T2.OBJECT_TYPE_ID (+) 
	    AND T0.BUSINESS_VARIABLE_CALCULATION = T4.RULE_ID (+) 
	    AND T0.LOGICAL_DATA_TYPE_ID = T5.LOGICAL_DATA_TYPE_ID (+) 
	    AND T0.REFERENCED_OBJECT_TYPE_ID = T7.OBJECT_TYPE_ID (+) 
	    AND T0.LOOKUP_LIST_ID = T8.LOOKUP_LIST_ID (+) 
	    AND T0.DOMINATOR_BV_ID = T19.BUSINESS_VARIABLE_ID (+) 
	    AND T0.INCL_OBJECT_RELATIONSHIP_ID = T22.OBJECT_RELATIONSHIP_ID (+) 
	    AND T0.TP_DICTIONARY_ID = T25.DICTIONARY_ID (+) 
	    AND ((T0.BUSINESS_VARIABLE_ID = 32337604 OR T0.BUSINESS_VARIABLE_ID = 32482104) )) 
	  ORDER BY T0.BUSINESS_VARIABLE_ID)
   WHERE rownum <= 50
/
