#!/bin/ksh

DB=$ORACLE_SID
OPERATOR="="

if [ $# -lt 1 ]; then
   echo "Missing parameter - object_name."
   exit 1
fi

OBJECT=$1
shift

while [ $# -ge 1 ]; do

  opt=$1
  shift

  case $opt in
     -d) DB=$1; shift ;;
    -eq) OPERATOR=$1; shift ;;
      *) echo "I don't know what $opt is...\n" ; exit 2;;
  esac

done


echo "

set feedback off
alter session set nls_date_format = 'DD-MON-YYYY HH24:MI:SS';
col owner format a10
col object_name format a40
col subobject_name format a10
col edition_name format a10

 select
 OWNER,
 OBJECT_NAME,
 --SUBOBJECT_NAME,
 --OBJECT_ID,
 --DATA_OBJECT_ID,
 OBJECT_TYPE,
 CREATED,
 LAST_DDL_TIME,
 --TIMESTAMP,
 STATUS
   from dba_objects
  where object_name $OPERATOR upper('$OBJECT')
order by object_name, owner, object_type ;

" |  $ORACLE_HOME/bin/sqlplus -s $SYSCONN@$DB


