#!/bin/ksh

DB=$ORACLE_SID
OPERATOR="="

if [ $# -lt 1 ]; then
   echo "Missing parameter - object_name."
   exit 1
fi

OBJECT=$1
shift

while [ $# -ge 1 ]; do

  opt=$1
  shift

  case $opt in
     -d) DB=$1; shift ;;
    -eq) OPERATOR=$1; shift ;;
      *) echo "I don't know what $opt is...\n" ; exit 2;;
  esac

done


echo "

col owner format a10
col object_name format a40
col subobject_name format a10
col edition_name format a10

 select
 OWNER,
 OBJECT_NAME,
 --SUBOBJECT_NAME,
 --OBJECT_ID,
 --DATA_OBJECT_ID,
 OBJECT_TYPE,
 CREATED,
 LAST_DDL_TIME,
 --TIMESTAMP,
 STATUS
   from dba_objects
  where object_name $OPERATOR upper('$OBJECT')
order by object_name, owner, object_type ;

" |  $ORACLE_HOME/bin/sqlplus -s awdba/awdba@$DB


exit

 OWNER                                                                                                                   VARCHAR2(30)
 OBJECT_NAME                                                                                                             VARCHAR2(128)
 SUBOBJECT_NAME                                                                                                          VARCHAR2(30)
 OBJECT_ID                                                                                                               NUMBER
 DATA_OBJECT_ID                                                                                                          NUMBER
 OBJECT_TYPE                                                                                                             VARCHAR2(19)
 CREATED                                                                                                                 DATE
 LAST_DDL_TIME                                                                                                           DATE
 TIMESTAMP                                                                                                               VARCHAR2(19)
 TEMPORARY                                                                                                               VARCHAR2(1)
 GENERATED                                                                                                               VARCHAR2(1)
 SECONDARY                                                                                                               VARCHAR2(1)
 NAMESPACE                                                                                                               NUMBER
 EDITION_NAME                                                                                                            VARCHAR2(30)


