#!/bin/ksh

DB=$ORACLE_SID
FREQUENCY=QUARTERLY
SCOPE=YEAR
DBFilter="db_name = upper('$ORACLE_SID')"

. /cloudsfs1/jenkins/OracleEnv.h 


###########################################
while [ $# -ge 1 ]; do

   opt=$1

   case $opt in 
	-db) shift; DBFilter="db_name = upper('$1')"; shift;;
	 -f)  shift; FREQUENCY=$1; shift;;
	 -s)  shift; SCOPE=$1; shift;;
	  *) echo "idk what $opt is." ; exit 2;;
   esac

done

###########################################

case $SCOPE in 
	  2YR) DateRange="s.begin_interval_time >= trunc(sysdate)-(365*2)" ;;
	 YEAR) DateRange="s.begin_interval_time >= trunc(sysdate)-365" ;;
      QUARTER) DateRange="s.begin_interval_time >= trunc(sysdate,'Q')" ;;
      LASTQTR) DateRange="s.begin_interval_time < trunc(sysdate,'Q') and s.begin_interval_time >= trunc(sysdate - (365/4),'Q')" ;;
	MONTH) DateRange="s.begin_interval_time >= trunc(sysdate,'MONTH')-30" ;;
	 WEEK) DateRange="s.begin_interval_time >= trunc(sysdate-7)" ;;
	    *) echo "IDK what $SCOPE is, in the context of snapshot date range"; exit 2;;
esac


WEEKLY="
 select trunc(s.begin_interval_time) - to_number(to_char(s.begin_interval_time,'D')) + 1 rpt_dte, i.db_name, i.dbid
	, min(s.snap_id) sample_snap_id, min(s.begin_interval_time) sample_date 
   from dba_hist_snapshot s , dba_hist_database_instance i 
  where i.instance_number = 1 
    and s.dbid = i.dbid 
    and s.startup_time = i.startup_time 
    and $DateRange
  group by trunc(s.begin_interval_time) - to_number(to_char(s.begin_interval_time,'D')) + 1
	, i.db_name, i.dbid
"

MONTHLY="
 select trunc(s.begin_interval_time,'MONTH') rpt_dte, i.db_name, i.dbid
	, min(s.snap_id) sample_snap_id, min(s.begin_interval_time) sample_date 
   from dba_hist_snapshot s , dba_hist_database_instance i 
  where i.instance_number = 1 
    and s.dbid = i.dbid 
    and s.startup_time = i.startup_time 
    and $DateRange
  group by trunc(s.begin_interval_time,'MONTH'), i.db_name, i.dbid
"

QUARTERLY="
 select trunc(s.begin_interval_time,'Q') rpt_dte, i.db_name, i.dbid
	, min(s.snap_id) sample_snap_id, min(s.begin_interval_time) sample_date 
   from dba_hist_snapshot s , dba_hist_database_instance i 
  where i.instance_number = 1 
    and s.dbid = i.dbid 
    and s.startup_time = i.startup_time 
    and $DateRange
  group by trunc(s.begin_interval_time,'Q'), i.db_name, i.dbid
"

DAILY="
 select trunc(s.begin_interval_time) rpt_dte, i.db_name, i.dbid
	, min(s.snap_id) sample_snap_id, min(s.begin_interval_time) sample_date 
   from dba_hist_snapshot s , dba_hist_database_instance i 
  where i.instance_number = 1 
    and s.dbid = i.dbid 
    and s.startup_time = i.startup_time 
    and $DateRange
  group by trunc(s.begin_interval_time), i.db_name, i.dbid
"

case $FREQUENCY in 
          DAILY) DateFilter=$DAILY ;;
         WEEKLY) DateFilter=$WEEKLY ;;
        MONTHLY) DateFilter=$MONTHLY ;;
      QUARTERLY) DateFilter=$QUARTERLY ;;
              *) echo "IDK what $FREQUENCY is, in the context of reporting delineation"; exit 2;;
esac

###########################################
###########################################
echo "

set pages 999
col mbsize_used format 999,999,999
col mbsize_file format 999,999,999
col mbsize_max format 999,999,999

select
	db_name,
	thedate,
	mbsize_used,
	mbsize_file,
	mbsize_max
   from (
	 select thedate,
		db_name,
		mbsize_file,
		mbsize_used,
		mbsize_max
	   from (
		 select rownum r,
			thedate,
			db_name,
			mbsize_file,
			mbsize_used,
			mbsize_max
		   from (
			 select trunc(thedate) thedate,
				db_name
				, sum(mbsize_file) mbsize_file
				, sum(mbsize_used) mbsize_used
				, sum(mbsize_max) mbsize_max
			   from    
				(
				 select snaps.rpt_dte thedate, snaps.sample_date, snaps.db_name,
					tablespace.tsname tablespace_name
					,usage.tablespace_size*block_size.value/1024/1024 mbsize_file
					,usage.tablespace_usedsize*block_size.value/1024/1024 mbsize_used
					,usage.tablespace_maxsize*block_size.value/1024/1024 mbsize_max
				   from dba_hist_tbspc_space_usage usage,
					dba_hist_tablespace   tablespace,
					v\$parameter                block_size
					, ( $DateFilter ) snaps
			          where 1=1
				    and usage.tablespace_id = tablespace.ts#
				    and usage.dbid = tablespace.dbid
				    and block_size.name     = 'db_block_size'
				    and snaps.dbid = usage.dbid
				    and snaps.sample_snap_id = usage.snap_id
				    and $DBFilter
				)
			 group by
				db_name,
				trunc(thedate)
			 order by
				db_name,
				trunc(thedate)
 )
 )
 );

" | sqlplus -s ${SYSCONN}@awrwh

